    # -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 04:04
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0.0'), default_currency=b'MXN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='template',
            name='photo_cover',
            field=models.FileField(upload_to='laduma/media/covers'),
        ),
        migrations.AlterField(
            model_name='template',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0.0'), default_currency=b'MXN', max_digits=10),
        ),
    ]
