# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170514_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='icon',
            field=models.FileField(default='null', upload_to='laduma/media/icons'),
            preserve_default=False,
        ),
    ]
